apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: nginx
    ssd: "true"
  name: nginx-fast-storage
spec:
  template:
    metadata:
      labels:
        app: nginx
        ssd: "true"
    spec:
      containers:
        - name: nginx
          image: nginx
      nodeSelector:
        ssd: "true"