apiVersion: v1
kind: Service
metadata:
  name: queue
  labels:
    app: worker-queue
    component: queue
    chapster: jobs
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: worker-queue
    component: queue